### ISSUE TITLE
p.59-60  執行結果與投影片不同

### ISSUE THREAD

**Issue by juyin529** [ntuaha/R_ETL_JIAWEI#14]
cl <- kmeans(mystocks.return_all, 5)
head(cl$cluster)

2014-01-02 2014-01-03 2014-01-06 2014-01-07 2014-01-08 
         1                   2                  5                  4              1 
2014-01-09 
         2 
結果與投影片不同。

s1 = c()
for(i in 1:5){
  i = as.character(i)
  s1[i] <- mean(mystocks.return_all[cl$cluster == i]) 
}
s1 <- sort(s1)
s1

```
       1                    5                       2                   4 
```

-0.022497385 -0.005969135 -0.002865778  0.000622311 
           3
0.007018467 
結果與投影片不同。

**Comment by sk413025** [comment]
謝謝幫忙測試 ~~
這是正常的，不用改 XDD
